In [20]:
import pickle
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder

In [21]:
df = pd.read_csv("BreastCancerDataset.csv")
df.head(7)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.1578,0.08089,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440,NaN
6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.1127,0.07400,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,NaN

In [22]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [23]:
df.isnull().sum()  # Checking null values #No Null Values in Dataset.

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [25]:
X = df.drop("diagnosis",axis=1)     # Extract the features (all columns except Attritions) from the dataset
le = LabelEncoder()
Y = le.fit_transform(df['diagnosis'])
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0])

In [27]:
# Spliting the data into train and test
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20,random_state=42)

Loading Preprocessor

In [28]:
# Load a preprocessor object from a pickled file
with open("/content/BCPreProprocessing.pkl","rb") as f:
    preprocessor=pickle.load(f)

In [29]:
preprocessor

ColumnTransformer(transformers=[('Standard_scaler', StandardScaler(),
                                 ['radius_mean', 'texture_mean',
                                  'perimeter_mean', 'area_mean',
                                  'smoothness_mean', 'compactness_mean',
                                  'concavity_mean', 'concave points_mean',
                                  'symmetry_mean', 'fractal_dimension_mean',
                                  'radius_se', 'texture_se', 'perimeter_se',
                                  'area_se', 'smoothness_se', 'compactness_se',
                                  'concavity_se', 'concave points_se',
                                  'symmetry_se', 'fractal_dimension_se',
                                  'radius_worst', 'texture_worst',
                                  'perimeter_worst', 'area_worst',
                                  'smoothness_worst', 'compactness_worst',
                                  'concavity_worst', 'concave points_worst',
                                  'symmetry_worst',
                                  'fractal_dimension_worst'])])

Transforming the data

In [30]:
# Transform the training data using the preprocessor object or PipeLine
Proprocessed_X_train = preprocessor.fit_transform(X_train)
Preprocessed_X_test=preprocessor.transform(X_test)

In [31]:
Y_train[57]

np.int64(0)

Balancing The Data

In [32]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_train_smote,Y_train_smote=smote.fit_resample(Proprocessed_X_train,Y_train)

In [59]:
#import seaborn as sns
sns.countplot(data=Y_train_smote, x='class')
plt.show()

TypeError: Data source must be a DataFrame or Mapping, not <class 'numpy.ndarray'>.

In [34]:
from collections import Counter
print("Actual Classes",Counter(Y_train))
print("SMOTE Classes",Counter(Y_train_smote))

Actual Classes Counter({np.int64(0): 286, np.int64(1): 169})
SMOTE Classes Counter({np.int64(0): 286, np.int64(1): 286})

In [36]:
#Y_train.value_counts

In [37]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(X_train_smote,Y_train_smote)
#Y_train[0]
#Preprocessed_X_train[0]

DecisionTreeClassifier()

In [38]:
from sklearn.metrics import accuracy_score,f1_score,classification_report
Y_predict=dt.predict(Preprocessed_X_test)    # predicting the model
acc=accuracy_score(Y_test,Y_predict)
acc

0.9122807017543859

In [39]:
f1_score=f1_score(Y_test,Y_predict)
f1_score

0.8888888888888888

In [40]:
print(classification_report(Y_test,Y_predict))

              precision    recall  f1-score   support

           0       0.96      0.90      0.93        71
           1       0.85      0.93      0.89        43

    accuracy                           0.91       114
   macro avg       0.90      0.92      0.91       114
weighted avg       0.92      0.91      0.91       114

In [41]:
params = {
    "criterion":("gini", "entropy"), #quality of split
    "splitter":("best", "random"), # searches the features for a split
    "max_depth":(list(range(1, 10))), #depth of tree range from 1 to 9
    "min_samples_split":[2, 3, 4,5,6,7],    #the minimum number of samples required to split internal node
    "min_samples_leaf":list(range(1, 10)),#minimum number of samples required to be at a leaf node,we are passing list which is range from 1 to 9
}

In [42]:
from sklearn.model_selection import GridSearchCV
tree_clf=DecisionTreeClassifier()
tree_cv=GridSearchCV(tree_clf,params,scoring="f1",n_jobs=-1,verbose=2,cv=5)

In [43]:
tree_cv.fit(X_train_smote,Y_train_smote)
best_params=tree_cv.best_params_
print(f"Best paramters: {best_params})")

Fitting 5 folds for each of 1944 candidates, totalling 9720 fits
Best paramters: {'criterion': 'entropy', 'max_depth': 9, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'random'})

In [54]:
Y_Pred=tree_cv.predict(Preprocessed_X_test)
print(classification_report(Y_test,Y_Pred))

              precision    recall  f1-score   support

           0       0.94      0.93      0.94        71
           1       0.89      0.91      0.90        43

    accuracy                           0.92       114
   macro avg       0.91      0.92      0.92       114
weighted avg       0.92      0.92      0.92       114

In [55]:
dt1=DecisionTreeClassifier(criterion='gini',max_depth=1,min_samples_leaf=1,min_samples_split=2,splitter='best')
#default parameters

In [46]:
dt1.fit(X_train_smote,Y_train_smote)
Y_predict=dt1.predict(Preprocessed_X_test)    # predicting the model
acc=accuracy_score(Y_test,Y_predict)
acc

0.9649122807017544

In [47]:
from sklearn.metrics import accuracy_score,f1_score,classification_report
f1_score=f1_score(Y_test,Y_predict)
f1_score

0.9545454545454546

In [48]:
print(classification_report(Y_test,Y_predict))

              precision    recall  f1-score   support

           0       0.99      0.96      0.97        71
           1       0.93      0.98      0.95        43

    accuracy                           0.96       114
   macro avg       0.96      0.97      0.96       114
weighted avg       0.97      0.96      0.97       114

In [56]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,f1_score,classification_report
rfclf=RandomForestClassifier()
rfclf.fit(X_train_smote,Y_train_smote)
Y_Predict=rfclf.predict(Preprocessed_X_test)

In [57]:
Y_Pred=rfclf.predict(Preprocessed_X_test)
accuracy_score(Y_test, Y_Pred)

0.9649122807017544

In [51]:
f1_score(Y_test, Y_Pred)

0.9523809523809523

In [52]:
print(classification_report(Y_test, Y_Pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97        71
           1       0.98      0.93      0.95        43

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

In [53]:
import numpy as np
grid_params={"n_estimators":[int(x) for x in np.linspace(start=200, stop=2000, num=5)],
             "max_features":['None','sqrt','log2'],
             "max_depth":[int(x) for x in np.linspace(10, 110, num=5)],
             "min_samples_split":[5, 10],
             "min_samples_leaf":[2, 4]}

rf_clf=RandomForestClassifier()
rf_cv=GridSearchCV(rf_clf,grid_params, scoring='f1',n_jobs=-1,verbose=2,cv=2)
rf_cv.fit(X_train_smote,Y_train_smote)
print("Best Parameters:",rf_cv.best_params_)

Fitting 2 folds for each of 300 candidates, totalling 600 fits
Best Parameters: {'max_depth': 85, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 1100}

In [ ]:
Y_Pred=rf_cv.predict(Preprocessed_X_test)
print(classification_report(Y_Pred,Y_test))

In [ ]:
accuracy=accuracy_score(Y_test,Y_Pred)
accuracy

In [ ]:
f1_score=f1_score(Y_test,Y_Pred)
f1_score

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()
gb.fit(X_train_smote,Y_train_smote)

In [ ]:
Y_Pred=gb.predict(Preprocessed_X_test)
Y_Pred

In [ ]:
from sklearn.metrics import classification_report,accuracy_score,f1_score
acc=accuracy_score(Y_test,Y_Pred)
acc

In [ ]:
f1_score=f1_score(Y_test,Y_Pred)
f1_score

In [ ]:
print(classification_report(Y_test,Y_Pred))

In [ ]:
from sklearn.model_selection import GridSearchCV
params={"learning_rate":[0.01, 0.03, 0.06, 0.1, 0.4, 0.5, 0.6, 0.7],
        "max_depth": [5, 6, 7, 8, 9, 10],
        "n_estimators": [50, 65, 80, 100]} #no. of trees, number of trees in the forest

In [ ]:
gb=GradientBoostingClassifier()
gb_grid=GridSearchCV(estimator=gb, scoring="f1", param_grid=params, n_jobs=-1, verbose=8,cv=3)
gb_grid.fit(X_train_smote, Y_train_smote)
print("Best Parameters",gb_grid.best_params)

In [ ]:
Y_Pred=gb_grid.predict(Preprocessed_X_test)
Y_Pred

In [ ]:
from sklearn.metrics import classification_report,accuracy_score,f1_score
acc=accuracy_score(Y_test,Y_Pred)
acc

In [ ]:
f1_score=f1_score(Y_test,Y_Pred)
f1_score

In [ ]:
print(classification_report(Y_test,Y_Pred))

In [ ]:
XGB2=GradientBoostingClassifier(n_estimators=50, max_depth=6, learning_rate=0.9)
XGB2.fit(X_train_smote, Y_train_smote)

In [ ]:
Y_Predict=XGB2.predict(Preprocessed_X_test)

In [ ]:
from sklearn.metrics import classification_report,accuracy_score,f1_score
acc=accuracy_score(Y_test,Y_Predict)
acc

In [ ]:
f1_score=f1_score(Y_test,Y_Predict)
f1_score

In [ ]:
print(classification_report(Y_test,Y_predict))

In [ ]:
with open("model1.pkl","wb") as f:
    pickle.dump(XGB2,f)

In [ ]:
from xgboost import XGBClassifier
xgb_r=XGBClassifier()
xgb_r.fit(X_train_smote,Y_train_smote)
Y_Pred=xgb_r.predict(Preprocessed_X_test)

In [ ]:
from sklearn.metrics import classification_report,accuracy_score,f1_score
acc=accuracy_score(Y_test,Y_Pred)
acc

In [ ]:
f1_score=f1_score(Y_test,Y_Pred)
f1_score

In [ ]:
print(classification_report(Y_test,Y_Pred))

In [ ]:
from sklearn.model_selection import GridSearchCV
params={"gamma": [0,0.1,0.2,0.4],
        "learning_rate": [0.01, 0.03, 0.06, 0.1],
        "max_depth": [5,6,7,8,9],
        "n_estimators": [50,65,80],
        "reg_alpha": [0,0.1,0.2,0.4],
        "reg_lambda": [0,0.1,0.2]}

In [ ]:
XGB=XGBClassifier(random_state=42, verbosity=0, silent=0)
grid_XGB=GridSearchCV(estimator=XGB,scoring="f1",refit=True,param_grid=params,cv=3,verbose=1,n_jobs=-1)

In [ ]:
grid_XGB.fit(X_train_smote,Y_train_smote)
print("Best Parameters:",grid_XGB.best_params_)

In [ ]:
grid_XGB.predict(Preprocessed_X_test)

In [ ]:
acc=accuracy_score(Y_test, Y_Pred)
acc

In [ ]:
f1_score=f1_score(Y_test,Y_Pred)
f1_score

In [ ]:
print(classification_report(Y_test, Y_Pred))

In [ ]:
XGBdefault=XGBClassifier(max_depth=3, leaning_rate=0.1, n_estimators=100, gamma=0, reg_lambda=1, reg_alpha=0)
XGBdefault.fit(Preprocessed_X_train, Y_train)
Y_Pred=XGBdefault.predict(preprocessed_X_test)

In [ ]:
from sklearn.metrics import classification_report,accuracy_score,f1_score
acc=accuracy_score(Y_test,Y_Pred)
acc

In [ ]:
f1_score=f1_score(Y_test,Y_Pred)
f1_score

In [ ]:
print(classification_report(Y_test,Y_Pred))

In [58]:
with open("DecisionTree_Model_BC.pkl","wb") as f:
  pickle.dump(grid_gradboost,f)

NameError: name 'grid_gradboost' is not defined